apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Adjust the access mode as needed
  storageClassName: standard  # Set the appropriate storage class
  resources:
    requests:
      storage: 10Gi  # Set the desired storage size
