apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "standard" # Adjust the storage class as needed
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # Adjust the storage size as needed

