apiVersion: v1
kind: Service
metadata:
  name: jenkins-headless-service
spec:
  selector:
    app: jenkins
  clusterIP: None
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
    - name: udp-port
      protocol: UDP
      port: 12345