apiVersion: v1
kind: Service
metadata:
  name: jenkins-loadbalancer-service
spec:
  selector:
    app: jenkins
  ports:
    - name: http
      protocol: http
      port: 80
      targetPort: 8080
  type: LoadBalancer



