apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins-statefulset
spec:
  serviceName: "jenkins-loadbalancer-service"
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      initContainers:
      - name: init-chown
        image: alpine
        command: ["sh", "-c", "chown -R 1000:1000 /var/jenkins_home"]
        volumeMounts:
        - name: jenkins-data
          mountPath: /var/jenkins_home
      containers:
      - name: jenkins-container
        image: "asia-south1-docker.pkg.dev/poshan-403704/poshan/express-app:tagversion"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        volumeMounts:
        - name: jenkins-data
          mountPath: /var/jenkins_home

  volumeClaimTemplates: []  
